### ISSUE TITLE
Can NOT save a 'case' if NOT press the '+' button

### ISSUE THREAD

**Issue by csbun** [bowenliang123/SandwidchRequestModifier#1]
You see...

**Comment by bowenliang123** [comment]
I admit it is really annoying ...
will fix it soon. Wait and see.

**Comment by csbun** [comment]
😜

**Comment by bowenliang123** [comment]
已更新到v1.2.4： 更正在没有选定用例的时候保存用例,提示保存为新用例。
https://github.com/bowenliang123/SailfishRequester/commit/964109cbea6faecbbcc23ef99934a529d3271a15

多谢xx提意见~

**Comment by csbun** [comment]
jjboom
