### ISSUE TITLE
重复发请求问题

### ISSUE THREAD

**Issue by LightGlobal** [bowenliang123/SandwidchRequestModifier#3]
请求时使用charles或者fiddler之类的抓包工具可以看到请求多发了，但是在chrome的开发者面板中却只能看到一个请求

**Comment by bowenliang123** [comment]
初步怀疑是因为需要注入前端js本地变量navigator.userAgent时候对页面进行reset导致的。
想问一下是只会出现在页面请求上而不是AJAX请求上吗？
