### ISSUE TITLE
是否可以支持指定域名生效

### ISSUE THREAD

**Issue by fangqi169** [bowenliang123/SandwidchRequestModifier#4]
只在某些域名下需要修改请求

**Comment by bowenliang123** [comment]
好啊，感觉这个需求有必要，我会考虑一下的。

**Comment by bowenliang123** [comment]
实现啦！

![2016-08-26 5 40 16](https://cloud.githubusercontent.com/assets/1935105/18001300/ab942506-6bb4-11e6-87d0-fbe03fdc773d.png)

可以通过配置域名关键字进行匹配了。

更新到v2.1.0版本上，已经发布到ChromeStore。
https://chrome.google.com/webstore/detail/gpfmnkbmokagemomhjafbmpkhajajkeh

可以通过自动更新，约6个小时左右。也可以通过“设置”-“拓展程序”-“开发者模式“-点击”立即更新拓展程序。“
